#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
PATCH_DIR="${ROOT_DIR}/ci/wine11-arm64ec/transfer-lanes/dlls-wave1-runtime/patches"
OUT_TSV="${1:-${ROOT_DIR}/docs/WINE11_ARM64EC_DLLS_WAVE1_PATCH_INDEX.tsv}"
OUT_MD="${2:-${ROOT_DIR}/docs/WINE11_ARM64EC_DLLS_WAVE1_PATCH_INDEX.md}"

fail() { printf '[wine11-dlls-wave1-index][error] %s\n' "$*" >&2; exit 1; }

[[ -d "${PATCH_DIR}" ]] || fail "Patch dir not found: ${PATCH_DIR}"

tmp_dir="$(mktemp -d /tmp/wine11-dlls-wave1-index-XXXXXX)"
trap 'rm -rf "${tmp_dir}"' EXIT

join_by() {
  local sep="$1"
  shift || true
  local out="" item
  for item in "$@"; do
    if [[ -z "${out}" ]]; then
      out="${item}"
    else
      out="${out}${sep}${item}"
    fi
  done
  printf '%s' "${out}"
}

emit_patch_paths() {
  local patch="$1"
  awk '
    /^diff --git a\// {
      path = $4
      sub(/^b\//, "", path)
      if (path != "/dev/null") print path
      next
    }
    /^\+\+\+ b\// {
      sub(/^\+\+\+ b\//, "", $0)
      if ($0 != "/dev/null") print $0
      next
    }
    /^--- a\// {
      sub(/^--- a\//, "", $0)
      if ($0 != "/dev/null") print $0
      next
    }
  ' "${patch}" | sort -u
}

mkdir -p "$(dirname -- "${OUT_TSV}")"
mkdir -p "$(dirname -- "${OUT_MD}")"

{
  printf 'patch_id\tpatch_file\tprimary_library\tlibraries\tpath_count\tchanged_paths\n'

  while IFS= read -r patch; do
    [[ -n "${patch}" ]] || continue
    patch_file="$(basename -- "${patch}")"
    patch_id="${patch_file%%-*}"

    mapfile -t paths < <(emit_patch_paths "${patch}")
    if [[ "${#paths[@]}" -eq 0 ]]; then
      paths=("UNKNOWN_PATH")
    fi

    libs_tmp="${tmp_dir}/libs-${patch_id}.txt"
    : > "${libs_tmp}"
    for p in "${paths[@]}"; do
      if [[ "${p}" == dlls/* ]]; then
        lib="${p#dlls/}"
        lib="${lib%%/*}"
        [[ -n "${lib}" ]] || lib="dlls"
        printf '%s\n' "${lib}" >> "${libs_tmp}"
      else
        printf '%s\n' "(non-dll:${p%%/*})" >> "${libs_tmp}"
      fi
    done

    mapfile -t libs < <(sort -u "${libs_tmp}")
    primary_library="${libs[0]}"
    for lib in "${libs[@]}"; do
      if [[ "${lib}" != "(non-dll:"* ]]; then
        primary_library="${lib}"
        break
      fi
    done

    libraries_joined="$(join_by "," "${libs[@]}")"
    paths_joined="$(join_by ";" "${paths[@]}")"

    printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
      "${patch_id}" \
      "${patch_file}" \
      "${primary_library}" \
      "${libraries_joined}" \
      "${#paths[@]}" \
      "${paths_joined}"
  done < <(find "${PATCH_DIR}" -maxdepth 1 -type f -name '*.patch' | sort)
} > "${OUT_TSV}"

patch_count="$(awk 'END { print (NR > 0 ? NR - 1 : 0) }' "${OUT_TSV}")"
library_count="$(awk -F'\t' 'NR > 1 { seen[$3] = 1 } END { c = 0; for (k in seen) c++; print c }' "${OUT_TSV}")"

{
  printf '# Wine11 ARM64EC DLLs Wave1 Patch Index\n\n'
  printf 'This index maps every `dlls-wave1-runtime` patch to its inferred target library.\n\n'
  printf '%s\n' '- source lane: `ci/wine11-arm64ec/transfer-lanes/dlls-wave1-runtime/patches`'
  printf '%s\n' '- generated by: `ci/wine11-arm64ec/generate-dlls-wave1-patch-index.sh`'
  printf '%s\n' "- generated at (UTC): \`$(date -u '+%Y-%m-%d %H:%M:%S')\`"
  printf '%s\n' "- total patches indexed: \`${patch_count}\`"
  printf '%s\n\n' "- distinct primary libraries: \`${library_count}\`"
  printf 'Primary index file:\n\n'
  printf '%s\n\n' '- `docs/WINE11_ARM64EC_DLLS_WAVE1_PATCH_INDEX.tsv`'
  printf '## Top Libraries By Patch Count\n\n'
  printf '| Library | Patch count |\n'
  printf '| --- | ---: |\n'
  awk -F'\t' 'NR > 1 { count[$3]++ } END { for (k in count) printf "%s\t%d\n", k, count[k] }' "${OUT_TSV}" \
    | sort -k2,2nr -k1,1 \
    | head -n 40 \
    | while IFS=$'\t' read -r lib count; do
        printf '| `%s` | %s |\n' "${lib}" "${count}"
      done
  printf '\n## Regeneration\n\n'
  printf '```bash\n'
  printf 'bash ci/wine11-arm64ec/generate-dlls-wave1-patch-index.sh\n'
  printf '```\n'
} > "${OUT_MD}"

printf '[wine11-dlls-wave1-index] Generated: %s (%s patches)\n' "${OUT_TSV}" "${patch_count}"
printf '[wine11-dlls-wave1-index] Generated: %s\n' "${OUT_MD}"
